# IR0 KERNEL MAKEFILE — MULTI-ARCH SCAFFOLD (x86-64 + ARM64)
#
# Sacred entry point for all developers (including the maintainer).
# Keep this file as an index: aliases, help, wiring, and explicit includes.
# Product/profile recipes and one-shot agent dumps do NOT belong here —
# put them under scripts/make/<domain>.mk and wire with an explicit -include.
#

KERNEL_ROOT := $(CURDIR)

# Default architecture (resolved after .config load)
ARCH ?=

CFLAGS_TARGET := -DIR0_DESKTOP


IR0_VERSION_MAJOR := 0
IR0_VERSION_MINOR := 0
IR0_VERSION_PATCH := 1
IR0_VERSION_SUFFIX := -rc5
IR0_VERSION_STRING := $(IR0_VERSION_MAJOR).$(IR0_VERSION_MINOR).$(IR0_VERSION_PATCH)$(IR0_VERSION_SUFFIX)

# Build information 

IR0_BUILD_DATE := $(shell LC_TIME=C date +"%b %d %Y")
IR0_BUILD_TIME := $(shell date +"%H:%M:%S")
IR0_BUILD_USER := $(shell whoami 2>/dev/null || echo "unknown")
IR0_BUILD_HOST := $(shell hostname 2>/dev/null || echo "localhost")
IR0_BUILD_CC := $(shell $(CC) --version 2>/dev/null | head -n1 | cut -d' ' -f1-3 || echo "gcc unknown")
# Build number - auto-increment on each build
IR0_BUILD_NUMBER := $(shell [ -f .build_number ] && cat .build_number || echo "1")
# Increment build number for next build (only if building kernel target)
-include .build_number_inc

# Load .config if it exists (generated by menuconfig).
# When .config is absent every CONFIG_* variable is empty and
# the ifneq(…,n) guards below default all subsystems to ON.
-include .config

CONFIG_ENABLE_USB_HOST ?= n
CONFIG_INIT_USB_HOST ?= n

# Tooling defaults from menuconfig (.config)
CONFIG_TOOL_AUTO_RUN_DEPTEST ?= n
CONFIG_TOOL_DEFAULT_DISK_FS ?= 0
CONFIG_TOOL_DEFAULT_DISK_SIZE_MB ?= 200
CONFIG_TOOL_UNIBUILD_DEFAULT_FILES ?=
CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE ?=
CONFIG_ARCH_X86_64 ?= y
CONFIG_ARCH_ARM64 ?= n

ifeq ($(ARCH),)
ifeq ($(CONFIG_ARCH_ARM64),y)
ARCH := arm64
else
ARCH := x86-64
endif
endif

ifdef arch
ARCH := $(arch)
endif

# Accept userspace-style triples so a sibling `ARCH=x86_64` env/MAKEFLAGS
# does not break make (command-line ARCH requires override).
ifeq ($(ARCH),x86_64)
override ARCH := x86-64
endif
ifeq ($(ARCH),amd64)
override ARCH := x86-64
endif
ifeq ($(ARCH),aarch64)
override ARCH := arm64
endif

ifeq ($(CONFIG_TOOL_DEFAULT_DISK_FS),1)
TOOL_DEFAULT_DISK_FS_NAME := fat32
else ifeq ($(CONFIG_TOOL_DEFAULT_DISK_FS),2)
TOOL_DEFAULT_DISK_FS_NAME := ext4
else
TOOL_DEFAULT_DISK_FS_NAME := minix
endif

# COMPILER CONFIGURATION (x86-64)

# Build tools
CC = gcc
LD = ld
ASM = nasm
NASM = nasm
QEMU = qemu-system-x86_64
PYTHON = python3
CROSS_COMPILE_ARM64 ?= aarch64-linux-gnu-

ifeq ($(ARCH),arm64)
CC = $(CROSS_COMPILE_ARM64)gcc
LD = $(CROSS_COMPILE_ARM64)ld
endif

# Flags
CFLAGS = -ffreestanding -nostdlib -g -Wall -Wextra -fno-stack-protector -fno-builtin
# Never build the kernel as PIE/PIC. With PIE, GCC keeps a PC base in %rbx and
# emits call*(%rbx+rel). A clobbered %rbx (context switch / interrupt) jumps into
# .bss — observed as #UD/#GP at current_process / fork_restore_audit (desk X).
CFLAGS += -fno-pie -fno-pic
ifeq ($(ARCH),arm64)
CFLAGS += -mgeneral-regs-only
else
CFLAGS += -m64 -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2
endif
NASMFLAGS = -f elf64 -I$(CURDIR)/

# Directories
BUILD_DIR = build
ISO_DIR = iso

# Targets
ifeq ($(ARCH),arm64)
DEFAULT_BUILD_TARGET := kernel-arm64.bin
else
DEFAULT_BUILD_TARGET := kernel-x64.iso
endif

# Product distribution (ISD). Recipes live in scripts/make/isd.mk.
# Compat: IR0_USERSPACE_ROOT/URL alias IR0_ISD_ROOT/URL.
-include scripts/make/isd.mk

all: $(DEFAULT_BUILD_TARGET)

# Public userspace ABI export (Linux `make headers_install` equivalent).
# Only includes/uapi leaves the kernel tree: a userspace package that needs a
# private kernel header is a broken boundary, not a missing include path.
UAPI_DIR = $(KERNEL_ROOT)/includes/uapi
DESTDIR ?= $(KERNEL_ROOT)

headers_install:
	@mkdir -p $(DESTDIR)/usr/include
	@cp -a $(UAPI_DIR)/. $(DESTDIR)/usr/include/
	@echo "✓ headers_install → $(DESTDIR)/usr/include ($$(find $(UAPI_DIR) -name '*.h' | wc -l) headers)"

menuconfig:
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py

menuconfig-en:
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --set TOOL_MENUCONFIG_LANG=en >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py

menuconfig-es:
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --set TOOL_MENUCONFIG_LANG=es >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py

defconfig:
	@cp $(KERNEL_ROOT)/setup/defconfig $(KERNEL_ROOT)/.config
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --sync
	@echo "✓ Default configuration written to .config"
	@echo "  Run 'make menuconfig' to customize, or 'make ir0' to build."

# Merge new Kconfig symbols into .config; keeps your explicit choices.
sync-menuconfig:
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --sync-capabilities
	@echo "✓ sync-menuconfig OK"

# Maintainer: refresh setup/defconfig after adding options to setup/Kconfig.
sync-menuconfig-defconfig:
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --sync-capabilities --defconfig-only
	@echo "✓ sync-menuconfig-defconfig OK"

# Preview what sync would change (exit 1 if drift detected).
sync-menuconfig-check:
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --sync-capabilities --dry-run

CFLAGS += $(CFLAGS_TARGET)

# Include paths
CFLAGS += -I$(KERNEL_ROOT)
CFLAGS += -I$(KERNEL_ROOT)/includes
# Public userspace ABI (exported by `make headers_install`).
CFLAGS += -I$(KERNEL_ROOT)/includes/uapi
# ktm/include before includes/ir0 so <ktm.h> is not shadowed by includes/ir0/ktm.h
CFLAGS += -I$(KERNEL_ROOT)/ktm/include
CFLAGS += -I$(KERNEL_ROOT)/includes/ir0
CFLAGS += -I$(KERNEL_ROOT)/mm
CFLAGS += -I$(KERNEL_ROOT)/arch/common
CFLAGS += -I$(KERNEL_ROOT)/arch/arm64
CFLAGS += -I$(KERNEL_ROOT)/kernel
CFLAGS += -I$(KERNEL_ROOT)/sched
CFLAGS += -I$(KERNEL_ROOT)/drivers
CFLAGS += -I$(KERNEL_ROOT)/fs
CFLAGS += -I$(KERNEL_ROOT)/net
CFLAGS += -I$(KERNEL_ROOT)/interrupt
CFLAGS += -MMD -MP

IR0_DEBUG_PMM ?= 0
IR0_DEBUG_WAIT ?= 0
IR0_DEBUG_PROC ?= 0
CFLAGS += -DIR0_DEBUG_PMM=$(IR0_DEBUG_PMM) -DIR0_DEBUG_WAIT=$(IR0_DEBUG_WAIT) -DIR0_DEBUG_PROC=$(IR0_DEBUG_PROC)

# C++ compile flags (freestanding kernel); matches %.o: %.cpp rule
ifeq ($(ARCH),arm64)
CXX_KERNEL_FLAGS = -ffreestanding -fno-exceptions -fno-rtti -fno-threadsafe-statics \
	-nostdlib -g -Wall -Wextra -fno-stack-protector -fno-builtin
else
CXX_KERNEL_FLAGS = -m64 -ffreestanding -fno-exceptions -fno-rtti -fno-threadsafe-statics \
	-mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 \
	-nostdlib -g -Wall -Wextra -fno-stack-protector -fno-builtin
endif
CXXFLAGS_COMPILE = $(CXX_KERNEL_FLAGS) $(CFLAGS)

# Assembler and linker flags (-I for asm_offsets.inc)
ASMFLAGS = -f elf64 -I$(CURDIR)/
LDFLAGS = -m elf_x86_64 -T arch/x86-64/linker.ld -Map=kernel-x64.map

ifeq ($(ARCH),arm64)
ASMFLAGS = -f elf64 -I$(CURDIR)/
LDFLAGS = -m aarch64elf -T arch/arm64/linker.ld -Map=kernel-arm64.map
endif


# CONFIGURACIÓN QEMU (ABSTRACCIÓN)

# Comandos QEMU por arquitectura
QEMU_64_CMD = qemu-system-x86_64

# Configuración QEMU básica
QEMU_MEMORY = 512M
QEMU_FLAGS = -no-reboot -no-shutdown
QEMU_TIMEOUT = 30

# Display profiles (GTK flags vary by QEMU version — probe once).
QEMU_DISPLAY_SDL = -display sdl2
QEMU_DISPLAY_NONE = -display none
QEMU_NGRAPHIC = -nographic
QEMU_NAME = -name IR0/Unix-x86_64
# Guest scale-2 glyphs are sharp; avoid host soft-scale blur.
QEMU_GTK_BASE = gtk,zoom-to-fit=off
# Probe optional GTK flags; never fail the build if unsupported.
QEMU_DISPLAY_GTK = $(shell \
	_opts='$(QEMU_GTK_BASE)'; \
	if $(QEMU) -display help 2>&1 | grep -q show-menubar; then _opts="$$_opts,show-menubar=off"; fi; \
	if $(QEMU) -display help 2>&1 | grep -q show-tabs; then _opts="$$_opts,show-tabs=off"; fi; \
	echo "-display $$_opts $(QEMU_NAME)")
QEMU_DISPLAY_GTK_DEBUG = -display gtk $(QEMU_NAME)

# Configuración por defecto
QEMU_DISPLAY = $(QEMU_DISPLAY_GTK)
QEMU_SERIAL = -serial stdio
QEMU_TEST_DISPLAY = $(QEMU_DISPLAY_NONE)  # Para pruebas automáticas

# Opciones de debugging y logging
QEMU_DEBUG_INT = -d int,cpu_reset
QEMU_DEBUG_EXEC = -d exec
QEMU_DEBUG_GUEST = -d guest_errors
QEMU_DEBUG_PAGE = -d page
QEMU_DEBUG_ALL = -d int,cpu_reset,exec,guest_errors,page
QEMU_LOG_FILE = -D qemu_debug.log

# Hardware soportado por IR0 Kernel
# Network: RTL8139
# User-mode networking: permite UDP pero ICMP saliente está limitado
# Para mejor soporte de ping, usar TAP networking (ver QEMU_NET_RTL8139_TAP)
QEMU_NET_RTL8139 = -netdev user,id=net0 -device rtl8139,netdev=net0

# TAP networking: Permite ping bidireccional (requiere permisos root y bridge configurado)
# Uso: 1) Crear bridge: sudo ip link add br0 type bridge
#      2) Agregar interfaz física: sudo ip link set eth0 master br0 (o wlan0)
#      3) Crear TAP: sudo ip tuntap add tap0 mode tap
#      4) Agregar TAP al bridge: sudo ip link set tap0 master br0
#      5) Activar interfaces: sudo ip link set br0 up && sudo ip link set tap0 up
#      6) Usar: make run-tap (o cambiar QEMU_NET_ALL a usar QEMU_NET_RTL8139_TAP)
QEMU_NET_RTL8139_TAP = -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device rtl8139,netdev=net0
ifneq ($(CONFIG_ENABLE_NETWORKING),n)
QEMU_NET_ALL = $(QEMU_NET_RTL8139)
else
QEMU_NET_ALL =
endif

# Audio: Sound Blaster 16 + Adlib (QEMU 8+ needs audiodev; ISA on default pc).
# Default backend is PulseAudio so the Linux host hears guest PCM (Doom /dev/audio).
# CI / headless: QEMU_AUDIO_BACKEND=none. Alternatives: alsa, sdl, pipewire.
QEMU_AUDIO_BACKEND ?= pa
QEMU_AUDIO_DEV = -audiodev $(QEMU_AUDIO_BACKEND),id=snd0
QEMU_AUDIO_SB16 = $(QEMU_AUDIO_DEV) -device sb16,audiodev=snd0
QEMU_AUDIO_ADLIB = -device adlib,audiodev=snd0
# Silent audiodev for automated smokes (no host mixer required).
QEMU_AUDIO_DEV_SILENT = -audiodev none,id=snd0
QEMU_AUDIO_SB16_SILENT = $(QEMU_AUDIO_DEV_SILENT) -device sb16,audiodev=snd0
ifneq ($(CONFIG_ENABLE_SOUND),n)
QEMU_AUDIO_ALL = $(QEMU_AUDIO_SB16) $(QEMU_AUDIO_ADLIB)
else
QEMU_AUDIO_ALL =
endif

# Storage: ATA/IDE disk (product run uses IR0_DISK → ISD image; smokes may override)
IR0_DISK ?= disk.img
# When 1, local run/smokes reuse DISK + inject stamps (skip stamp rm). CI leaves unset/0.
IR0_DEV_PERSIST ?= 0
# Dev disk image (override to ISD development disk.img when persist=1).
ifeq ($(IR0_DEV_PERSIST),1)
  _ISD_DEV_DISK := $(IR0_USERSPACE_ROOT)/out/x86_64/images/development/disk.img
  ifneq ($(wildcard $(_ISD_DEV_DISK)),)
    IR0_DEV_DISK := $(_ISD_DEV_DISK)
  else
    IR0_DEV_DISK ?= $(IR0_DISK)
  endif
else
  IR0_DEV_DISK ?= $(IR0_DISK)
endif
QEMU_STORAGE_IDE = -drive file=$(IR0_DISK),format=raw,if=ide,index=0

# Serial: COM1 para debug
QEMU_SERIAL_COM1 = -serial stdio

# Guest outb(0xf4) → QEMU process exit (halt/poweroff). Needed with -no-shutdown.
QEMU_ISA_DEBUG_EXIT = -device isa-debug-exit,iobase=0xf4,iosize=0x04

QEMU_HW_IR0_ALL = $(QEMU_NET_ALL) $(QEMU_AUDIO_ALL) $(QEMU_STORAGE_IDE) $(QEMU_SERIAL_COM1) $(QEMU_ISA_DEBUG_EXIT)

# Full host IR0 tree at guest /heart/dennis/src (writable; long names OK).
# Default on for interactive run*; IR0_DENNIS_9P=0 to skip.
IR0_DENNIS_9P ?= 1
QEMU_DENNIS_9P = -fsdev local,id=dennisfs,path=$(KERNEL_ROOT),security_model=none \
	-device virtio-9p-pci,fsdev=dennisfs,mount_tag=dennis,disable-modern=on
ifeq ($(IR0_DENNIS_9P),0)
QEMU_DENNIS_9P =
endif

QEMU_64_FLAGS = -cdrom

# KERNEL OBJECTS 

KERNEL_OBJS = \
	kernel/main.o \
	kernel/boot_init.o \
    kernel/cmdline.o \
    kernel/rootfs_base.o \
    kernel/process/core.o \
    kernel/process/create.o \
    kernel/process/domains.o \
    kernel/process/mm_struct.o \
    kernel/process/files_struct.o \
    kernel/process/fork.o \
    kernel/process/exec.o \
    kernel/process/exit.o \
    kernel/process/wait.o \
    kernel/process/wait_state.o \
    kernel/process/saved_context.o \
    kernel/process/saved_environ.o \
    kernel/process/signal_enter.o \
    kernel/process/fdtable.o \
    kernel/process/pseudo_fd_bind.o \
    kernel/process/mm.o \
    kernel/process/signals.o \
    kernel/vdso.o \
    kernel/debug/fase_audit.o \
    kernel/clock_wait.o \
    kernel/credentials.o \
    kernel/power/power_manag.o \
    kernel/kexec.o \
    kernel/syscalls.o \
    kernel/syscalls/fs_syscalls.o \
    kernel/syscalls/fs_path_syscalls.o \
    kernel/syscalls/validate_user.o \
    kernel/syscalls/mm_syscalls.o \
    kernel/syscalls/socket_syscalls.o \
    kernel/syscalls/process_syscalls.o \
    kernel/syscalls/io_syscalls.o \
    kernel/syscalls/epoll_syscalls.o \
    kernel/syscalls/time_syscalls.o \
    kernel/syscalls/syscall_dispatch.o \
    kernel/sock_udp.o \
    kernel/sock_icmp.o \
    kernel/sock_stream.o \
    kernel/sock_inet_ioctl.o \
    kernel/sysv_shm.o \
    kernel/memfd.o \
    kernel/eventfd.o \
    kernel/timerfd.o \
    kernel/posix_shm.o \
    kernel/input_events.o \
    kernel/elf_loader.o \
    kernel/driver_registry.o \
    kernel/resource_registry.o \
    kernel/ipc.o \
    kernel/futex.o \
    kernel/net_compat.o \
    ktm/klog.o \
    ktm/d1_13_malloc_pf_diag.o \
    sched/sched.o \
    sched/sched_switch.o \
    sched/sched_resched.o \
    sched/switch/arch_context_switch.o \
    kernel/console_backend.o

ifeq ($(CONFIG_KTM),y)
KERNEL_OBJS += \
    ktm/event_ring.o \
    ktm/deferred.o \
    ktm/user_canary.o \
    ktm/stack_watch.o \
    ktm/transport_serial.o \
    ktm/ktm_klog.o \
    ktm/registry.o \
    ktm/snapshot.o \
    ktm/assert.o \
    ktm/checkpoint.o \
    ktm/fault.o \
    ktm/invariant_global.o \
    ktm/scenario.o \
    tests/ktm/scenarios/process_lifecycle.o \
    tests/ktm/scenarios/pipe_lifecycle.o \
    tests/ktm/scenarios/mm_cow_fork.o \
    tests/ktm/scenarios/mm_vma.o \
    tests/ktm/scenarios/mm_page_tables.o \
    tests/ktm/scenarios/mm_steady_state.o \
    tests/ktm/scenarios/vfs_devfs.o \
    tests/ktm/scenarios/shell_redir.o \
    tests/ktm/scenarios/mm_oom_class.o \
    tests/ktm/scenarios/process_wait_drain.o \
    tests/ktm/scenarios/graphics_fb.o \
    tests/ktm/scenarios/input_events0.o \
    tests/ktm/scenarios/vfs_open_flags.o \
    tests/ktm/scenarios/process_reclaim_exit.o \
    tests/ktm/scenarios/process_exec.o \
    tests/ktm/scenarios/process_fork_rollback.o \
    ktm/userdev.o \
    ktm/ktm_flight.o \
    ktm/ktm_panic_class.o \
    ktm/ktm_ctx_snapshot.o \
    ktm/ktm_probe_diag.o \
    $(KTM_D1_DIAG_OBJS)
endif

# In-kernel test suite: linked only in kernel-x64-test.bin (make tests)
KERNEL_TEST_OBJS = \
	kernel/test/test_runner.o \
	kernel/test/test_syscall.o \
	kernel/test/test_procfs.o \
	kernel/test/test_debug_contracts.o \
	kernel/test/test_process.o \
	kernel/test/test_cred_access.o \
	kernel/test/test_resource_registry.o \
	kernel/test/test_allocator.o \
	kernel/test/test_path.o \
	kernel/test/test_string.o \
	kernel/test/test_ktm_sched.o \
	kernel/test/test_mmap_null_placement.o \
	kernel/test/test_signal_segv_deliver.o \
	kernel/test/test_brk_post_exec.o \
	kernel/test/test_tty_canon_read.o \
	ktm/ktm_invariant.o \
	ktm/ktm_sched_gate.o


# Scheduler backend selection from menuconfig (ops via <ir0/sched.h>).
# Policy 1 (CFS) is an honest RR alias — same backend object, different policy name.
ifeq ($(CONFIG_SCHEDULER_POLICY),2)
SCHED_BACKEND_OBJS = sched/priority_sched.o
else
SCHED_BACKEND_OBJS = sched/rr_sched.o
endif
KERNEL_OBJS += $(SCHED_BACKEND_OBJS)
ifneq ($(CONFIG_SCHEDULER_POLICY),)
CFLAGS += -DCONFIG_SCHEDULER_POLICY=$(CONFIG_SCHEDULER_POLICY)
else
CFLAGS += -DCONFIG_SCHEDULER_POLICY=0
endif

MEMORY_OBJS = \
	mm/allocator.o \
	mm/paging.o \
	mm/pmm.o \
	mm/kmem.o \
	mm/page_fault.o

LIB_OBJS = \
    kernel/lib/vga.o \
    kernel/lib/logging.o \
    kernel/lib/boot_log_hostshare.o \
    kernel/lib/oops.o \
    kernel/lib/signals.o \
    kernel/lib/pipe.o \
    kernel/lib/copy_user.o \
    kernel/lib/open_flags.o \
    kernel/lib/stat_user.o \
    kernel/lib/named_fifo.o \
    kernel/lib/named_devnode.o \
    kernel/lib/supervise_path.o \
    kernel/lib/named_symlink.o \
    kernel/lib/path_user.o \
    kernel/lib/path_routed.o \
    kernel/lib/utsname_info.o \
    kernel/lib/console.o \
    kernel/lib/ps2_set1.o \
    kernel/lib/ps2_mouse_pkt.o \
    kernel/lib/ash_smoke.o \
    kernel/lib/debug_trap.o \
    kernel/lib/fb.o \
    kernel/lib/input.o \
    kernel/lib/utimens.o \
    kernel/lib/exec_read_trace.o \
    kernel/lib/blockdev.o \
    kernel/lib/mm_port.o \
    kernel/lib/rtc_calendar.o \
    kernel/lib/video_backend.o \
    kernel/lib/input_backend.o \
    kernel/lib/audio_backend.o \
    includes/string.o

INTERRUPT_OBJS_X86_64 = \
    interrupt/arch/idt.o \
    interrupt/arch/x86-64/early_idt.o \
    interrupt/arch/pic.o \
    interrupt/arch/isr_handlers.o \
    interrupt/arch/keyboard.o \
    interrupt/arch/x86-64/isr_stubs_64.o \
    interrupt/arch/x86-64/early_idt_stubs.o

# ARM64: do not pull lidt / isr_stubs_64 — GIC is in ARCH_OBJS.
INTERRUPT_OBJS_ARM64 = \
    arch/arm64/sources/irq_portable_stubs.o

ifeq ($(ARCH),arm64)
INTERRUPT_OBJS := $(INTERRUPT_OBJS_ARM64)
else
INTERRUPT_OBJS := $(INTERRUPT_OBJS_X86_64)
endif

DRIVER_OBJS = \
    drivers/driver_bootstrap.o \
    drivers/IO/ps2.o \
    drivers/timer/pit/pit.o \
    drivers/timer/clock_system.o \
    drivers/timer/rtc/rtc.o \
    drivers/timer/hpet/hpet.o \
    drivers/timer/hpet/find_hpet.o \
    drivers/timer/acpi/acpi_pm.o \
    drivers/timer/lapic/lapic.o \
    drivers/storage/block_dev.o \
    drivers/storage/fs_types.o \
	drivers/video/console.o \
	drivers/video/console_font.o \
	drivers/video/font_terminus_14x28.o \
	drivers/video/console_renderer.o \
	drivers/video/typewriter.o \
	drivers/init_drv.o \
	drivers/virtio/virtio_9p.o \
	$(MULTILANG_DRIVER_SUPPORT_OBJ)

# COM1 16550 only on x86; ARM64 uses arch/arm64/sources/serial_io_arm64.c (PL011).
ifneq ($(ARCH),arm64)
DRIVER_OBJS += drivers/serial/serial.o
endif

HEART_SRC_BLOB := $(KERNEL_ROOT)/includes/generated/heart_src_blob.h

$(HEART_SRC_BLOB): \
		$(KERNEL_ROOT)/scripts/gen_heart_src_blob.py \
		$(KERNEL_ROOT)/includes/ir0/heart_src_probe.h \
		$(KERNEL_ROOT)/includes/ir0/pseudo_fs.h \
		$(KERNEL_ROOT)/includes/ir0/heartfs.h \
		$(KERNEL_ROOT)/includes/ir0/version.h \
		$(KERNEL_ROOT)/includes/ir0/sock_stream.h \
		$(KERNEL_ROOT)/includes/ir0/ahci_api.h \
		$(KERNEL_ROOT)/arch/common/arch_portable.h \
		$(KERNEL_ROOT)/kernel/syscalls.c
	@python3 $(KERNEL_ROOT)/scripts/gen_heart_src_blob.py \
		--root $(KERNEL_ROOT) --out $(HEART_SRC_BLOB)

fs/heartfs.o: $(HEART_SRC_BLOB)

FS_OBJS = \
    fs/vfs.o \
    fs/path.o \
    fs/chmod.o \
    fs/permissions.o \
    fs/flock.o \
    fs/pseudo_fs_registry.o \
    fs/pseudo_fs_nodes.o \
    fs/heartfs.o \
    fs/procfs.o \
    fs/devfs.o \
    fs/sysfs.o \
    fs/hostshare_9p.o

ifneq ($(CONFIG_ENABLE_FS_MINIX),n)
FS_OBJS += fs/minix_fs.o
CFLAGS += -DCONFIG_ENABLE_FS_MINIX=1
else
CFLAGS += -DCONFIG_ENABLE_FS_MINIX=0
endif

ifneq ($(CONFIG_ENABLE_FS_TMPFS),n)
FS_OBJS += fs/tmpfs.o
CFLAGS += -DCONFIG_ENABLE_FS_TMPFS=1
else
CFLAGS += -DCONFIG_ENABLE_FS_TMPFS=0
endif

ifneq ($(CONFIG_ENABLE_FS_SIMPLEFS),n)
FS_OBJS += fs/simplefs.o
CFLAGS += -DCONFIG_ENABLE_FS_SIMPLEFS=1
else
CFLAGS += -DCONFIG_ENABLE_FS_SIMPLEFS=0
endif

ifneq ($(CONFIG_ENABLE_FS_FAT16),n)
FS_OBJS += fs/fat16_fs.o
FS_OBJS += fs/fat16_disk.o
CFLAGS += -DCONFIG_ENABLE_FS_FAT16=1
else
CFLAGS += -DCONFIG_ENABLE_FS_FAT16=0
endif

ifneq ($(CONFIG_ENABLE_FS_EXT2),n)
FS_OBJS += fs/ext2_disk.o
CFLAGS += -DCONFIG_ENABLE_FS_EXT2=1
else
CFLAGS += -DCONFIG_ENABLE_FS_EXT2=0
endif

DISK_OBJS = \
    drivers/disk/partition.o

# ============================================
# CONDITIONAL SUBSYSTEM OBJECTS
# ============================================
# Controlled by .config (generated by menuconfig).
# Pattern: ifneq(…,n) makes the subsystem compile when the variable
# is empty (no .config) OR "y", keeping the build backward-compatible.

# Networking (IPv4 stack + RTL8139 NIC driver)
ifneq ($(CONFIG_ENABLE_NETWORKING),n)
NET_OBJS = \
    net/net.o \
    net/arp.o \
    net/ip.o \
    net/icmp.o \
    net/udp.o \
    net/tcp.o \
    net/dhcp.o \
    net/dns.o
NET_DRIVER_OBJS = \
    drivers/net/net_drivers.o
ifneq ($(CONFIG_DRV_NIC_RTL8139),n)
ifeq ($(ARCH),x86-64)
NET_DRIVER_OBJS += drivers/net/rtl8139.o
CFLAGS += -DCONFIG_DRV_NIC_RTL8139=1
else
CFLAGS += -DCONFIG_DRV_NIC_RTL8139=0
endif
else
CFLAGS += -DCONFIG_DRV_NIC_RTL8139=0
endif
ifneq ($(CONFIG_DRV_NIC_VIRTIO_NET),n)
ifeq ($(ARCH),x86-64)
NET_DRIVER_OBJS += drivers/net/virtio_net.o
CFLAGS += -DCONFIG_DRV_NIC_VIRTIO_NET=1
else
CFLAGS += -DCONFIG_DRV_NIC_VIRTIO_NET=0
endif
else
CFLAGS += -DCONFIG_DRV_NIC_VIRTIO_NET=0
endif
CFLAGS += -DCONFIG_DRV_NIC_E1000=0
CFLAGS += -DCONFIG_ENABLE_NETWORKING=1
else
NET_OBJS =
NET_DRIVER_OBJS =
CFLAGS += -DCONFIG_DRV_NIC_RTL8139=0
CFLAGS += -DCONFIG_DRV_NIC_VIRTIO_NET=0
CFLAGS += -DCONFIG_DRV_NIC_E1000=0
CFLAGS += -DCONFIG_ENABLE_NETWORKING=0
endif

# Sound (Sound Blaster 16 + Adlib OPL2 + ISA DMA)
ifneq ($(CONFIG_ENABLE_SOUND),n)
SOUND_OBJS = \
    drivers/audio/sound_blaster.o \
    drivers/audio/adlib.o \
    drivers/dma/dma.o
CFLAGS += -DCONFIG_ENABLE_SOUND=1
else
SOUND_OBJS =
CFLAGS += -DCONFIG_ENABLE_SOUND=0
endif

# Bluetooth (HCI-UART transport + device manager)
ifneq ($(CONFIG_ENABLE_BLUETOOTH),n)
BLUETOOTH_OBJS = \
    drivers/bluetooth/hci_uart.o \
    drivers/bluetooth/hci_core.o \
    drivers/bluetooth/bluetooth_iface.o \
    drivers/bluetooth/bt_device.o \
    drivers/bluetooth/bt_sysfs.o \
    drivers/bluetooth/bluetooth_init.o
CFLAGS += -DCONFIG_ENABLE_BLUETOOTH=1
else
BLUETOOTH_OBJS = \
    drivers/bluetooth/bluetooth_iface_stub.o
CFLAGS += -DCONFIG_ENABLE_BLUETOOTH=0
endif

# USB host scaffold (PCI scan)
ifneq ($(CONFIG_ENABLE_USB_HOST),n)
USB_OBJS = drivers/usb/usb_host.o
CFLAGS += -DCONFIG_ENABLE_USB_HOST=1
else
USB_OBJS =
CFLAGS += -DCONFIG_ENABLE_USB_HOST=0
endif

ifneq ($(CONFIG_INIT_USB_HOST),n)
CFLAGS += -DCONFIG_INIT_USB_HOST=1
else
CFLAGS += -DCONFIG_INIT_USB_HOST=0
endif

# PS/2 mouse
ifneq ($(CONFIG_ENABLE_MOUSE),n)
MOUSE_OBJS = drivers/IO/ps2_mouse.o
CFLAGS += -DCONFIG_ENABLE_MOUSE=1
else
MOUSE_OBJS =
CFLAGS += -DCONFIG_ENABLE_MOUSE=0
endif

# PC speaker
ifneq ($(CONFIG_ENABLE_PC_SPEAKER),n)
PC_SPEAKER_OBJS = drivers/IO/pc_speaker.o
CFLAGS += -DCONFIG_ENABLE_PC_SPEAKER=1
else
PC_SPEAKER_OBJS =
CFLAGS += -DCONFIG_ENABLE_PC_SPEAKER=0
endif

# ATA core / block layer
ifneq ($(CONFIG_ENABLE_STORAGE_ATA),n)
STORAGE_ATA_OBJS = \
    drivers/storage/ata.o \
    drivers/storage/ata_helpers.o
CFLAGS += -DCONFIG_ENABLE_STORAGE_ATA=1
else
STORAGE_ATA_OBJS =
CFLAGS += -DCONFIG_ENABLE_STORAGE_ATA=0
endif

ifneq ($(CONFIG_ENABLE_STORAGE_ATA),n)
ifneq ($(CONFIG_ENABLE_STORAGE_ATA_BLOCK),n)
STORAGE_ATA_BLOCK_OBJS = drivers/storage/ata_block.o
CFLAGS += -DCONFIG_ENABLE_STORAGE_ATA_BLOCK=1
else
STORAGE_ATA_BLOCK_OBJS =
CFLAGS += -DCONFIG_ENABLE_STORAGE_ATA_BLOCK=0
endif
else
STORAGE_ATA_BLOCK_OBJS =
CFLAGS += -DCONFIG_ENABLE_STORAGE_ATA_BLOCK=0
endif

STORAGE_AHCI_OBJS = drivers/storage/ahci.o
STORAGE_NVME_OBJS = drivers/storage/nvme.o

# VBE framebuffer (VGA text console is always compiled)
ifneq ($(CONFIG_ENABLE_VBE),n)
VBE_OBJS = drivers/video/vbe.o
CFLAGS += -DCONFIG_ENABLE_VBE=1
else
VBE_OBJS =
CFLAGS += -DCONFIG_ENABLE_VBE=0
endif

# Driver boot init selection flags
ifneq ($(CONFIG_INIT_PS2_CONTROLLER),n)
CFLAGS += -DCONFIG_INIT_PS2_CONTROLLER=1
else
CFLAGS += -DCONFIG_INIT_PS2_CONTROLLER=0
endif
ifneq ($(CONFIG_INIT_PC_SPEAKER),n)
CFLAGS += -DCONFIG_INIT_PC_SPEAKER=1
else
CFLAGS += -DCONFIG_INIT_PC_SPEAKER=0
endif
ifneq ($(CONFIG_INIT_STORAGE_ATA),n)
CFLAGS += -DCONFIG_INIT_STORAGE_ATA=1
else
CFLAGS += -DCONFIG_INIT_STORAGE_ATA=0
endif
ifneq ($(CONFIG_INIT_STORAGE_ATA_BLOCK),n)
CFLAGS += -DCONFIG_INIT_STORAGE_ATA_BLOCK=1
else
CFLAGS += -DCONFIG_INIT_STORAGE_ATA_BLOCK=0
endif
ifneq ($(CONFIG_INIT_SOUND_DRIVERS),n)
CFLAGS += -DCONFIG_INIT_SOUND_DRIVERS=1
else
CFLAGS += -DCONFIG_INIT_SOUND_DRIVERS=0
endif
ifneq ($(CONFIG_INIT_MOUSE_DRIVER),n)
CFLAGS += -DCONFIG_INIT_MOUSE_DRIVER=1
else
CFLAGS += -DCONFIG_INIT_MOUSE_DRIVER=0
endif
ifneq ($(CONFIG_INIT_NETWORK_STACK),n)
CFLAGS += -DCONFIG_INIT_NETWORK_STACK=1
else
CFLAGS += -DCONFIG_INIT_NETWORK_STACK=0
endif
ifneq ($(CONFIG_INIT_BLUETOOTH_DRIVER),n)
CFLAGS += -DCONFIG_INIT_BLUETOOTH_DRIVER=1
else
CFLAGS += -DCONFIG_INIT_BLUETOOTH_DRIVER=0
endif

# Debug flags — only passed when explicitly set to y in .config
ifeq ($(CONFIG_DEBUG_MEMORY_ALLOCATOR),y)
CFLAGS += -DCONFIG_DEBUG_MEMORY_ALLOCATOR=1
else
CFLAGS += -DCONFIG_DEBUG_MEMORY_ALLOCATOR=0
endif
ifeq ($(CONFIG_DEBUG_PMM),y)
CFLAGS += -DCONFIG_DEBUG_PMM=1
else
CFLAGS += -DCONFIG_DEBUG_PMM=0
endif
ifeq ($(CONFIG_DEBUG_PAGING),y)
CFLAGS += -DCONFIG_DEBUG_PAGING=1
else
CFLAGS += -DCONFIG_DEBUG_PAGING=0
endif
ifeq ($(CONFIG_DEBUG_PAGE_FAULTS),y)
CFLAGS += -DCONFIG_DEBUG_PAGE_FAULTS=1
else
CFLAGS += -DCONFIG_DEBUG_PAGE_FAULTS=0
endif
ifeq ($(CONFIG_DEBUG_D1_DIAG),y)
CFLAGS += -DCONFIG_DEBUG_D1_DIAG=1
KTM_D1_DIAG_OBJS := ktm/d1_12_read_diag.o ktm/d1_16_tty_read_diag.o
else
CFLAGS += -DCONFIG_DEBUG_D1_DIAG=0
KTM_D1_DIAG_OBJS :=
endif
ifeq ($(CONFIG_DEBUG_PROCESS),y)
CFLAGS += -DCONFIG_DEBUG_PROCESS=1
else
CFLAGS += -DCONFIG_DEBUG_PROCESS=0
endif
ifeq ($(CONFIG_DEBUG_SCHEDULER),y)
CFLAGS += -DCONFIG_DEBUG_SCHEDULER=1
else
CFLAGS += -DCONFIG_DEBUG_SCHEDULER=0
endif
ifeq ($(CONFIG_DEBUG_VFS),y)
CFLAGS += -DCONFIG_DEBUG_VFS=1
else
CFLAGS += -DCONFIG_DEBUG_VFS=0
endif
ifeq ($(CONFIG_DEBUG_SYSCALLS),y)
CFLAGS += -DCONFIG_DEBUG_SYSCALLS=1
else
CFLAGS += -DCONFIG_DEBUG_SYSCALLS=0
endif
ifeq ($(CONFIG_DEBUG_KEYBOARD),y)
CFLAGS += -DCONFIG_DEBUG_KEYBOARD=1
else
CFLAGS += -DCONFIG_DEBUG_KEYBOARD=0
endif
ifeq ($(CONFIG_DEBUG_MEMORY_COALESCING),y)
CFLAGS += -DCONFIG_DEBUG_MEMORY_COALESCING=1
else
CFLAGS += -DCONFIG_DEBUG_MEMORY_COALESCING=0
endif
ifeq ($(CONFIG_DEBUG_MEMORY_STATS),y)
CFLAGS += -DCONFIG_DEBUG_MEMORY_STATS=1
else
CFLAGS += -DCONFIG_DEBUG_MEMORY_STATS=0
endif
ifeq ($(CONFIG_DEBUG_FORK),y)
CFLAGS += -DCONFIG_DEBUG_FORK=1
else
CFLAGS += -DCONFIG_DEBUG_FORK=0
endif
ifeq ($(CONFIG_DEBUG_FS_MOUNT),y)
CFLAGS += -DCONFIG_DEBUG_FS_MOUNT=1
else
CFLAGS += -DCONFIG_DEBUG_FS_MOUNT=0
endif
ifeq ($(CONFIG_DEBUG_SYSCALL_PARAMS),y)
CFLAGS += -DCONFIG_DEBUG_SYSCALL_PARAMS=1
else
CFLAGS += -DCONFIG_DEBUG_SYSCALL_PARAMS=0
endif

# Tick rate (PIT frequency / kernel jiffies); default matches setup/defconfig
CONFIG_TICK_RATE_HZ ?= 1000
CFLAGS += -DCONFIG_TICK_RATE_HZ=$(CONFIG_TICK_RATE_HZ)

# Product boot always loads /sbin/init (legacy KERNEL_DEBUG_SHELL removed).
CFLAGS += -DCONFIG_KERNEL_DEBUG_SHELL=0

# Force /sbin/init boot path for userspace smoke ISO (overrides autoconf in config.h)
ifneq ($(USERSPACE_INIT_BUILD),)
CFLAGS += -DIR0_USERSPACE_INIT_BOOT=1
# USERSPACE_EAGER_MM=1 disables lazy anon mmap + brk (bisect only; default is lazy).
ifeq ($(USERSPACE_EAGER_MM),1)
CFLAGS += -DCONFIG_LAZY_ANON_MMAP=0 -DCONFIG_LAZY_BRK_HEAP=0
endif
endif

ARCH_OBJS_COMMON = \
    arch/common/arch_interface.o \
    arch/common/boot_log.o

ARCH_OBJS_X86_64 = \
    arch/x86-64/sources/arch_x64.o \
    arch/x86-64/sources/platform.o \
    arch/x86-64/sources/gdt.o \
    arch/x86-64/sources/tss_x64.o \
    arch/x86-64/sources/arch_early.o \
    arch/x86-64/sources/user_mode.o \
    arch/x86-64/sources/arch_fork.o \
    arch/x86-64/sources/fork_asm_hooks.o \
    arch/x86-64/sources/arch_task_ops.o \
    arch/x86-64/sources/arch_syscall_frame.o \
    arch/x86-64/sources/arch_signal.o \
    arch/x86-64/sources/arch_switch.o \
    arch/x86-64/sources/arch_mm.o \
    arch/x86-64/sources/arch_irq_init.o \
    arch/x86-64/sources/arch_page_fault.o \
    arch/x86-64/sources/idt_arch_x64.o \
    arch/x86-64/sources/fault.o \
    arch/x86-64/sources/debug_dump.o \
    arch/x86-64/sources/arch_pf_debug.o \
    arch/x86-64/sources/mm_ops.o \
    arch/x86-64/vdso/blob.o \
    arch/x86-64/vdso/vdso_blob_embed.o \
    arch/x86-64/asm/boot_x64.o \
    arch/x86-64/asm/syscall_entry_64.o \
    arch/x86-64/asm/syscall_insn_entry_64.o \
    sched/switch/switch_x64.o

ARCH_OBJS_ARM64 = \
    arch/common/boot_log.o \
    arch/arm64/sources/arch_arm64.o \
    arch/arm64/sources/arch_early.o \
    arch/arm64/sources/interrupts.o \
    arch/arm64/sources/timer.o \
    arch/arm64/sources/mm_ops.o \
    arch/arm64/sources/pl011.o \
    arch/arm64/sources/serial_io_arm64.o \
    arch/arm64/sources/gic_v2.o \
    arch/arm64/sources/syscall_early.o \
    arch/arm64/sources/boot_stub.o \
    arch/arm64/sources/mmu_early.o \
    arch/arm64/sources/exc_early.o \
    arch/arm64/sources/slice_hello.o \
    arch/arm64/sources/portable_string.o \
    arch/arm64/sources/vectors.o \
    arch/arm64/sources/syscall_stub.o \
    arch/arm64/sources/platform.o \
    arch/arm64/sources/arch_fork.o \
    arch/arm64/sources/fork_asm_hooks.o \
    arch/arm64/sources/arch_task_ops.o \
    arch/arm64/sources/arch_syscall_frame.o \
    arch/arm64/sources/arch_signal.o \
    arch/arm64/sources/arch_switch.o \
    arch/arm64/sources/arch_mm.o \
    arch/arm64/sources/arch_irq_init.o \
    arch/arm64/sources/arch_page_fault.o \
    arch/arm64/sources/freestanding_stubs.o \
    arch/arm64/sources/switch_early_asm.o \
    arch/arm64/sources/switch_early.o \
    arch/arm64/sources/process_early.o \
    arch/arm64/sources/elf_load_early.o \
    arch/arm64/sources/hello_embed.o \
    arch/arm64/sources/busybox_load_early.o \
    arch/arm64/sources/rootfs_early.o \
    arch/arm64/sources/busybox_embed.o \
    arch/arm64/sources/rr_early.o \
    arch/arm64/sources/rr_early_stubs.o \
    arch/arm64/sources/virtio_blk_early.o \
    arch/arm64/sources/virtio_net_early.o \
    drivers/virtio/virtio_mmio.o \
    arch/arm64/sources/first_switch.o \
    build/arm64-boot/rr_sched.o \
    build/arm64-boot/switch_arm64.o

build/arm64-boot/rr_sched.o: sched/rr_sched.c
	@mkdir -p build/arm64-boot
	@aarch64-linux-gnu-gcc $(ARM64_BOOT_CFLAGS) -DARCH_ARM64=1 \
		-I$(KERNEL_ROOT)/sched -I$(KERNEL_ROOT)/includes \
		-I$(KERNEL_ROOT)/includes/ir0 -I$(KERNEL_ROOT)/arch/common \
		-I$(KERNEL_ROOT) \
		-c sched/rr_sched.c -o build/arm64-boot/rr_sched.o

build/arm64-boot/switch_arm64.o: sched/switch/switch_arm64.c
	@mkdir -p build/arm64-boot
	@aarch64-linux-gnu-gcc $(ARM64_BOOT_CFLAGS) -I$(KERNEL_ROOT)/sched \
		-I$(KERNEL_ROOT)/includes -I$(KERNEL_ROOT)/includes/ir0 \
		-I$(KERNEL_ROOT)/arch/common \
		-c sched/switch/switch_arm64.c -o build/arm64-boot/switch_arm64.o

ifeq ($(ARCH),arm64)
ARCH_OBJS := $(ARCH_OBJS_ARM64)
else
ARCH_OBJS := $(ARCH_OBJS_COMMON) $(ARCH_OBJS_X86_64)
endif

CPP_OBJS = \
	cpp/runtime/compat.o

# Multi-language driver objects (Rust and C++) - Optional, only included if enabled
RUST_DRIVER_OBJS = 
CPP_DRIVER_OBJS = 
MULTILANG_DRIVER_SUPPORT_OBJ = 

# Include example drivers only if KERNEL_ENABLE_EXAMPLE_DRIVERS is enabled
# These are test/example drivers and should not be compiled by default
-include .example_drivers_enabled
ifneq ($(CONFIG_ENABLE_EXAMPLE_DRIVERS),)
ifeq ($(CONFIG_ENABLE_EXAMPLE_DRIVERS),y)
RUST_DRIVER_OBJS += rust/drivers/rust_simple_driver.o
CPP_DRIVER_OBJS += cpp/examples/cpp_example.o
MULTILANG_DRIVER_SUPPORT_OBJ += drivers/multilang_drivers.o
CFLAGS += -DKERNEL_ENABLE_EXAMPLE_DRIVERS=1
else
CFLAGS += -DKERNEL_ENABLE_EXAMPLE_DRIVERS=0
endif
else ifeq ($(ENABLE_EXAMPLE_DRIVERS),1)
RUST_DRIVER_OBJS += rust/drivers/rust_simple_driver.o
CPP_DRIVER_OBJS += cpp/examples/cpp_example.o
MULTILANG_DRIVER_SUPPORT_OBJ += drivers/multilang_drivers.o
CFLAGS += -DKERNEL_ENABLE_EXAMPLE_DRIVERS=1
else
CFLAGS += -DKERNEL_ENABLE_EXAMPLE_DRIVERS=0
endif

# All objects (kernel sin tests in-kernel)
ALL_OBJS = $(KERNEL_OBJS) $(MEMORY_OBJS) $(LIB_OBJS) $(INTERRUPT_OBJS) \
           $(DRIVER_OBJS) $(FS_OBJS) $(ARCH_OBJS) $(DISK_OBJS) \
           $(CPP_OBJS) $(CPP_DRIVER_OBJS) $(RUST_DRIVER_OBJS) \
           $(NET_OBJS) $(NET_DRIVER_OBJS) $(SOUND_OBJS) $(BLUETOOTH_OBJS) \
           $(USB_OBJS) $(MOUSE_OBJS) $(VBE_OBJS) $(PC_SPEAKER_OBJS) \
           $(STORAGE_ATA_OBJS) $(STORAGE_ATA_BLOCK_OBJS) $(STORAGE_AHCI_OBJS) \
           $(STORAGE_NVME_OBJS)

# Keep test-only entry objects separate: their IR0_KERNEL_TESTS references must
# never contaminate an incremental production link.
KERNEL_TEST_ENTRY_OBJS = build/test/kernel/main.o build/test/kernel/boot_init.o

# Objetos para kernel con tests in-kernel (make tests / kernel-tests)
ALL_OBJS_TEST = $(filter-out kernel/main.o kernel/boot_init.o,$(KERNEL_OBJS)) \
                $(KERNEL_TEST_ENTRY_OBJS) $(KERNEL_TEST_OBJS) $(MEMORY_OBJS) $(LIB_OBJS) $(INTERRUPT_OBJS) \
                $(DRIVER_OBJS) $(FS_OBJS) $(ARCH_OBJS) $(DISK_OBJS) \
                $(CPP_OBJS) $(CPP_DRIVER_OBJS) $(RUST_DRIVER_OBJS) \
                $(NET_OBJS) $(NET_DRIVER_OBJS) $(SOUND_OBJS) $(BLUETOOTH_OBJS) \
                $(USB_OBJS) $(MOUSE_OBJS) $(VBE_OBJS) $(PC_SPEAKER_OBJS) \
                $(STORAGE_ATA_OBJS) $(STORAGE_ATA_BLOCK_OBJS) $(STORAGE_AHCI_OBJS) \
           $(STORAGE_NVME_OBJS)

AUTOCONF_HDR := $(KERNEL_ROOT)/includes/generated/autoconf.h
ifneq ($(wildcard $(KERNEL_ROOT)/.config),)
$(AUTOCONF_HDR): $(KERNEL_ROOT)/.config
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --sync >/dev/null
$(ALL_OBJS): $(AUTOCONF_HDR)
$(ALL_OBJS_TEST): $(AUTOCONF_HDR)
endif

# BUILD RULES

# x86-64 vDSO (musl AT_SYSINFO_EHDR / __vdso_clock_gettime)
VDSO_DIR = arch/x86-64/vdso
VDSO_SO = $(VDSO_DIR)/vdso.so
VDSO_OBJ = $(VDSO_DIR)/vdso.o
VDSO_EMBED = $(VDSO_DIR)/vdso_blob_embed.o
VDSO_CFLAGS = -m64 -fPIC -fno-stack-protector -fno-builtin -nostdlib -c

$(VDSO_OBJ): $(VDSO_DIR)/vdso.S
	@echo "  AS      $< (vDSO)"
	@$(CC) $(VDSO_CFLAGS) $< -o $@

$(VDSO_SO): $(VDSO_OBJ) $(VDSO_DIR)/vdso.lds
	@echo "  LD      $@ (vDSO)"
	@$(LD) -m elf_x86_64 -shared -nostdlib -T $(VDSO_DIR)/vdso.lds -o $@ $(VDSO_OBJ)

$(VDSO_EMBED): $(VDSO_SO)
	@echo "  OBJCOPY $< → $@"
	@cd $(VDSO_DIR) && objcopy -I binary -O elf64-x86-64 -B i386:x86-64 \
		--rename-section .data=.rodata,alloc,load,readonly,data,contents \
		--add-section .note.GNU-stack=/dev/null \
		--set-section-flags .note.GNU-stack=noload,readonly \
		vdso.so vdso_blob_embed.o

# Compile C files
%.o: %.c
	@echo "  CC      $<"
	@$(CC) $(CFLAGS) \
		-DIR0_BUILD_DATE_STRING="\"$(IR0_BUILD_DATE)\"" \
		-DIR0_BUILD_TIME_STRING="\"$(IR0_BUILD_TIME)\"" \
		-DIR0_BUILD_USER_STRING="\"$(IR0_BUILD_USER)\"" \
		-DIR0_BUILD_HOST_STRING="\"$(IR0_BUILD_HOST)\"" \
		-DIR0_BUILD_CC_STRING="\"$(IR0_BUILD_CC)\"" \
		-DIR0_BUILD_NUMBER_STRING="\"$(IR0_BUILD_NUMBER)\"" \
		-c $< -o $@

# Compile C++ files
%.o: %.cpp
	@echo "  CXX     $<"
	@g++ $(CXXFLAGS_COMPILE) -c $< -o $@

# Compile Rust files (using unibuild script)
%.o: %.rs
	@echo "  RUST    $<"
	@$(KERNEL_ROOT)/scripts/unibuild.sh -rust $<

# Compile ASM files
%.o: %.asm
	@echo "  ASM     $<"
	@$(ASM) $(ASMFLAGS) $< -o $@

ifeq ($(ARCH),arm64)
%.o: %.S
	@echo "  AS      $<"
	@$(CC) $(CFLAGS) -c $< -o $@

# switch_early.S → switch_early_asm.o (avoid clash with switch_early.c)
arch/arm64/sources/hello_embed.o: arch/arm64/sources/hello_embed.S $(MUSL_AARCH64_HELLO)
	@$(MAKE) -s musl-aarch64-hello
	@echo "  AS      $<"
	@$(CC) $(CFLAGS) -c arch/arm64/sources/hello_embed.S -o $@

arch/arm64/sources/switch_early_asm.o: arch/arm64/sources/switch_early.S
	@echo "  AS      $<"
	@$(CC) $(CFLAGS) -c $< -o $@
endif


# Link kernel
kernel-x64.bin: $(ALL_OBJS) arch/x86-64/linker.ld
	@echo "  LD      $@"
	@$(LD) $(LDFLAGS) -o $@ $(ALL_OBJS)
	@echo "✓ Kernel linked: $@"
	@echo "  BUILD   Incrementing build number..."
	@if [ -f .build_number ]; then \
		BUILD_NUM=$$(cat .build_number); \
		BUILD_NUM=$$((BUILD_NUM + 1)); \
		echo $$BUILD_NUM > .build_number; \
	else \
		echo "1" > .build_number; \
	fi

kernel-arm64.bin: $(ARCH_OBJS) arch/arm64/linker.ld
	@echo "  LD      $@"
	@$(LD) $(LDFLAGS) -o $@ $(ARCH_OBJS)
	@echo "✓ Kernel linked: $@"

# Create ISO
kernel-x64.iso: kernel-x64.bin arch/x86-64/grub.cfg
	@echo "  ISO     $@"
	@rm -rf iso
	@mkdir -p iso/boot/grub
	@cp arch/x86-64/grub.cfg iso/boot/grub/
	@cp kernel-x64.bin iso/boot/
	@echo "Running grub-mkrescue (will print errors if it fails)..."
	@grub-mkrescue -o $@ iso
	@echo "✓ ISO created: $@"

# Kernel con tests in-kernel (solo al hacer make tests / kernel-tests)
# config.h documents IR0_KERNEL_TESTS; Makefile ensures it for this target.
# kmain must be compiled with that flag: a leftover kernel-x64.bin main.o
# would skip kernel_test_run_all() and make kernel-tests time out.
kernel-x64-test.bin: $(ALL_OBJS_TEST) arch/x86-64/linker.ld
	@echo "  LD      $@ (with in-kernel tests)"
	@$(LD) $(LDFLAGS) -o $@ $(ALL_OBJS_TEST)
	@echo "✓ Kernel (test) linked: $@"

build/test/kernel/%.o: kernel/%.c
	@mkdir -p $(@D)
	@echo "  CC      $< (test variant)"
	@$(CC) $(CFLAGS) -DIR0_KERNEL_TESTS=1 \
		-DIR0_BUILD_DATE_STRING="\"$(IR0_BUILD_DATE)\"" \
		-DIR0_BUILD_TIME_STRING="\"$(IR0_BUILD_TIME)\"" \
		-DIR0_BUILD_USER_STRING="\"$(IR0_BUILD_USER)\"" \
		-DIR0_BUILD_HOST_STRING="\"$(IR0_BUILD_HOST)\"" \
		-DIR0_BUILD_CC_STRING="\"$(IR0_BUILD_CC)\"" \
		-DIR0_BUILD_NUMBER_STRING="\"$(IR0_BUILD_NUMBER)\"" \
		-c $< -o $@

kernel-x64-test.iso: kernel-x64-test.bin arch/x86-64/grub.cfg
	@echo "  ISO     $@"
	@rm -rf iso_test
	@mkdir -p iso_test/boot/grub
	@cp arch/x86-64/grub.cfg iso_test/boot/grub/
	@cp kernel-x64-test.bin iso_test/boot/kernel-x64.bin
	@grub-mkrescue -o $@ iso_test
	@rm -rf iso_test
	@echo "✓ ISO (test) created: $@"

# Create a raw disk image used by QEMU. If you want a persistent filesystem
# you can format and populate this image separately. This target will
# create a raw disk image if it doesn't already exist.
# Supports filesystem selection via FS=minix|fat16|fat32|ext4 and size via SIZE=MB (legacy)
# For new usage, use: make create-disk [filesystem] [size]
disk.img:
	@if [ -f $@ ]; then \
		echo "  DISK    $@ already exists"; \
	else \
		echo "  DISK    creating $@ using scripts/create_disk.sh"; \
		if [ -n "$(FS)" ]; then \
			if [ -n "$(SIZE)" ]; then \
				./scripts/create_disk.sh $(FS) $(SIZE) --output $@; \
			else \
				./scripts/create_disk.sh $(FS) --output $@; \
			fi; \
		else \
			./scripts/create_disk.sh --output $@; \
		fi; \
	fi
	@echo "✓ Disk image ready: $@"

# ============================================
# BUILD CONFIGURATION
# ============================================

# Parallel jobs: default to all CPU cores (override: make -j1 or PARALLEL_JOBS=1)
NPROC := $(shell nproc 2>/dev/null || echo 4)
PARALLEL_JOBS ?= $(NPROC)

# Top-level invocations compile object files in parallel unless -j is already set.
ifeq ($(MAKELEVEL), 0)
  ifeq ($(filter -j%,$(MAKEFLAGS)),)
    MAKEFLAGS += -j$(PARALLEL_JOBS)
  endif
endif

# ARCH is already set at the top of the file

# Legacy alias: `make ir0-auto` / `make auto` (same as default parallel build)
.PHONY: auto ir0-auto
auto ir0-auto: ir0


# Process architecture parameter and .config selection.
ifneq ($(filter $(ARCH),x86-64 arm64),$(ARCH))
$(error Unsupported architecture: $(ARCH). Valid values: x86-64, arm64 (aliases: x86_64, aarch64))
endif

ifeq ($(CONFIG_ARCH_X86_64),y)
CFLAGS += -DCONFIG_ARCH_X86_64=1
else
CFLAGS += -DCONFIG_ARCH_X86_64=0
endif

ifeq ($(CONFIG_ARCH_ARM64),y)
CFLAGS += -DCONFIG_ARCH_ARM64=1
else
CFLAGS += -DCONFIG_ARCH_ARM64=0
endif

ifeq ($(ARCH),x86-64)
CFLAGS += -DARCH_X86_64 -DARCH_X86
QEMU = qemu-system-x86_64
else
CFLAGS += -DARCH_ARM64
QEMU = qemu-system-aarch64
endif

# ============================================
# BUILD TARGETS
# ============================================

# Objetivo principal: warnings como errores (replica CI / toolchains estrictos).
ir0: CFLAGS += -Werror

ifeq ($(CONFIG_TOOL_AUTO_RUN_DEPTEST),y)
IR0_PRECHECK_TARGETS := deptest
else
IR0_PRECHECK_TARGETS :=
endif

# Default target
ir0: $(IR0_PRECHECK_TARGETS) $(DEFAULT_BUILD_TARGET)

# Windows build target
windows win:
	@echo "Building IR0 Kernel for Windows..."
	@$(MAKE) -f Makefile.win ir0

windows-clean win-clean:
	@echo "Cleaning Windows build artifacts..."
	@$(MAKE) -f Makefile.win clean

# QEMU COMMANDS

# Run with GUI and disk (default) - ALL IR0 SUPPORTED HARDWARE
# Note: This target does NOT call clean-net or rebuild with special flags
# It simply runs the existing kernel ISO. Use 'make run-tap' for TAP networking.
# Product console: ISD-owned disk for PROFILE (no per-binary inject).
# First time: make first-boot PROFILE=minimal && make run PROFILE=minimal
# Legacy inject: IR0_LEGACY_USERSPACE=1 make run  (load-userspace-*)
# Ungrab mouse/keyboard in QEMU GTK: Ctrl+Alt+G (SETUP.md).
run: kernel-x64-userspace.iso
	@if [ "$${IR0_LEGACY_USERSPACE:-0}" = "1" ]; then \
		if [ "$${IR0_WITH_DEVTOOLS:-1}" = "1" ]; then \
			$(MAKE) -s load-userspace-devtools; \
		else \
			$(MAKE) -s load-userspace-runit; \
		fi; \
		echo "Running IR0/Unix (LEGACY inject → disk.img)..."; \
		qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
			$(QEMU_HW_IR0_ALL) $(QEMU_DENNIS_9P) \
			-m 512M -no-reboot \
			$(QEMU_DISPLAY); \
	else \
		$(MAKE) run-isd; \
	fi

# Run with GUI and serial debug output - ALL IR0 SUPPORTED HARDWARE
run-debug: kernel-x64-userspace.iso
	@if [ "$${IR0_LEGACY_USERSPACE:-0}" = "1" ]; then \
		if [ "$${IR0_WITH_DEVTOOLS:-1}" = "1" ]; then $(MAKE) -s load-userspace-devtools; \
		else $(MAKE) -s load-userspace-runit; fi; \
		qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
			$(QEMU_HW_IR0_ALL) $(QEMU_DENNIS_9P) \
			-m 512M -no-reboot -no-shutdown \
			$(QEMU_DISPLAY_GTK_DEBUG) \
			-serial stdio \
			-monitor telnet:127.0.0.1:1234,server,nowait \
			-d guest_errors,int $(QEMU_LOG_FILE); \
	else \
		$(MAKE) -s ensure-isd-disk; \
		echo "Running IR0+ISD debug (PROFILE=$(ISD_PROFILE) DISK=$(IR0_ISD_DISK))..."; \
		qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
			-drive file=$(IR0_ISD_DISK),format=raw,if=ide,index=0 \
			$(QEMU_NET_ALL) $(QEMU_AUDIO_ALL) $(QEMU_ISA_DEBUG_EXIT) $(QEMU_DENNIS_9P) \
			-m 512M -no-reboot -no-shutdown \
			$(QEMU_DISPLAY_GTK_DEBUG) \
			-serial stdio \
			-monitor telnet:127.0.0.1:1234,server,nowait \
			-d guest_errors,int $(QEMU_LOG_FILE); \
	fi

# run-bootlog: defined in scripts/make/hostshare-boot.mk (serial + optional 9p boot log).
# Human interactive with serial in-terminal: make run-debug.

run-fullscreen: kernel-x64-userspace.iso
	@if [ "$${IR0_LEGACY_USERSPACE:-0}" = "1" ]; then \
		if [ "$${IR0_WITH_DEVTOOLS:-1}" = "1" ]; then $(MAKE) -s load-userspace-devtools; \
		else $(MAKE) -s load-userspace-runit; fi; \
		qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
			$(QEMU_HW_IR0_ALL) $(QEMU_DENNIS_9P) \
			-m 512M -no-reboot \
			-display gtk,zoom-to-fit=on,full-screen=on $(QEMU_NAME); \
	else \
		$(MAKE) -s ensure-isd-disk; \
		qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
			-drive file=$(IR0_ISD_DISK),format=raw,if=ide,index=0 \
			$(QEMU_NET_ALL) $(QEMU_AUDIO_ALL) $(QEMU_SERIAL_COM1) $(QEMU_ISA_DEBUG_EXIT) $(QEMU_DENNIS_9P) \
			-m 512M -no-reboot \
			-display gtk,zoom-to-fit=on,full-screen=on $(QEMU_NAME); \
	fi

# Run without disk
run-nodisk:
	@echo "run-nodisk retired: product boot requires runit rootfs (use: make run)"
	@exit 2

run-dbgshell:
	@echo "run-dbgshell retired: use runit/getty/ash (make run-console)"
	@exit 2

# Run in console mode (-nographic). Product path: ISD disk for PROFILE.
# Legacy inject: IR0_LEGACY_USERSPACE=1 make run-console
run-console: kernel-x64-userspace.iso
	@if [ "$${IR0_LEGACY_USERSPACE:-0}" = "1" ]; then \
		$(MAKE) -s load-userspace-runit; \
		echo "Running IR0/Unix console (LEGACY inject → disk.img)..."; \
		qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
			$(QEMU_HW_IR0_ALL) $(QEMU_DENNIS_9P) \
			-m 512M -no-reboot -no-shutdown \
			$(QEMU_NGRAPHIC); \
	else \
		$(MAKE) -s ensure-isd-disk; \
		echo "Running IR0+ISD console (PROFILE=$(ISD_PROFILE) DISK=$(IR0_ISD_DISK))..."; \
		qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
			-drive file=$(IR0_ISD_DISK),format=raw,if=ide,index=0 \
			$(QEMU_NET_ALL) $(QEMU_AUDIO_ALL) $(QEMU_SERIAL_COM1) $(QEMU_ISA_DEBUG_EXIT) \
			$(QEMU_DENNIS_9P) \
			-m 512M -no-reboot -no-shutdown \
			$(QEMU_NGRAPHIC); \
	fi

# Run with TAP networking (permite ping bidireccional, requiere root y bridge configurado)
# Pasos previos (bridge y TAP):
#   1. sudo ip link add br0 type bridge
#   2. sudo ip link set eth0 master br0  (reemplaza eth0 con tu interfaz)
#   3. sudo ip tuntap add tap0 mode tap
#   4. sudo ip link set tap0 master br0
#   5. sudo ip link set br0 up && sudo ip link set tap0 up
run-tap: load-userspace-runit
	@echo "🚀 Running IR0 Kernel with TAP networking (full ICMP support)..."
	@echo "   Hardware: RTL8139, ATA/IDE, Serial, PS/2, VGA (audio disabled)"
	@echo "   ⚠️  Requires: root permissions and TAP interface configured"
	@if [ ! -c /dev/net/tun ]; then \
		echo "ERROR: TUN/TAP device not available. Install: sudo modprobe tun"; \
		exit 1; \
	fi
	@echo "   📝 Building kernel with TAP networking support (auto-configure IP)..."
	@$(MAKE) clean-net 2>/dev/null || true
	@$(MAKE) CFLAGS="$(CFLAGS) -DIR0_TAP_NETWORKING" kernel-x64-userspace.iso
	@echo "   🎮 Starting QEMU (audio disabled to avoid ALSA errors)..."
	sudo qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
		$(QEMU_NET_RTL8139_TAP) $(QEMU_STORAGE_IDE) $(QEMU_SERIAL_COM1) \
		-m 512M -no-reboot -no-shutdown \
		$(QEMU_DISPLAY) \
		$(QEMU_DEBUG_GUEST) $(QEMU_LOG_FILE)

# Run with ICMP ping support (user-mode networking, no TAP/bridge needed)
# Enables unprivileged ICMP sockets via sysctl so QEMU SLiRP can forward ping.
# Only needs sudo once to set the sysctl; QEMU itself runs unprivileged.
# Guest IP: 10.0.2.15, Gateway/DNS: 10.0.2.2 (always pingable)
# Internet: ping 8.8.8.8 works after sysctl is set.
run-ping: kernel-x64-userspace.iso load-userspace-runit
	@echo "  PING    Checking ICMP socket permissions..."
	@CURRENT=$$(cat /proc/sys/net/ipv4/ping_group_range 2>/dev/null); \
	if echo "$$CURRENT" | grep -q "^0[[:space:]]"; then \
		echo "          ping_group_range already configured: $$CURRENT"; \
	else \
		echo "          Setting net.ipv4.ping_group_range (requires sudo once)..."; \
		sudo sysctl -w net.ipv4.ping_group_range="0 2147483647" || { \
			echo "ERROR: Could not set ping_group_range. Run manually:"; \
			echo "  sudo sysctl -w net.ipv4.ping_group_range=\"0 2147483647\""; \
			exit 1; \
		}; \
	fi
	@echo "  PING    Launching QEMU with user-mode networking (ICMP enabled)"
	@echo "          Guest: 10.0.2.15 | Gateway: 10.0.2.2 | DNS: 10.0.2.3"
	@echo "          Try: ping 10.0.2.2   (gateway, always works)"
	@echo "          Try: ping 8.8.8.8    (internet, needs sysctl)"
	qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
		$(QEMU_HW_IR0_ALL) \
		-m 512M -no-reboot -no-shutdown \
		$(QEMU_DISPLAY)

# Debug mode (detailed QEMU logging) - ALL IR0 SUPPORTED HARDWARE
debug: kernel-x64-userspace.iso load-userspace-runit
	@echo "Running IR0 Kernel (debug) with all supported hardware..."
	@echo "   Hardware: RTL8139, SB16, ATA/IDE, Serial, PS/2, VGA"
	qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
		$(QEMU_HW_IR0_ALL) \
		-m 512M -no-reboot -no-shutdown \
		$(QEMU_DISPLAY) \
		-d int,cpu_reset,guest_errors $(QEMU_LOG_FILE)

# QEMU con servidor GDB: inspección de memoria, breakpoints, single-step.
run-gdb: kernel-x64-userspace.iso load-userspace-runit
	@echo "  GDB     QEMU waiting for GDB on localhost:1234"
	@echo "          In another terminal run:"
	@echo "            gdb -x scripts/kernel.gdb"
	@echo "          Breakpoints on kmain and kernel_panic are set automatically."
	qemu-system-x86_64 -cdrom kernel-x64-userspace.iso \
		$(QEMU_SERIAL_COM1) -drive file=disk.img,format=raw,if=ide,index=0 \
		-m 512M -no-reboot -no-shutdown -display none -net none \
		-s -S

# Create disk image (wrapper for scripts/create_disk.sh)
# Usage: make create-disk [filesystem] [size]
# Examples:
#   make create-disk              # Create 200MB MINIX disk (default)
#   make create-disk minix 500    # Create 500MB MINIX disk
#   make create-disk fat32        # Create FAT32 disk (default size)
#   make create-disk fat32 500    # Create 500MB FAT32 disk
#   make create-disk ext4 1000    # Create 1GB ext4 disk
#   make create-disk hints        # Show help
create-disk:
	@ARGS="$(filter-out $@,$(MAKECMDGOALS))"; \
	if [ -z "$$ARGS" ]; then \
		./scripts/create_disk.sh "$(TOOL_DEFAULT_DISK_FS_NAME)" "$(CONFIG_TOOL_DEFAULT_DISK_SIZE_MB)"; \
	elif [ "$$ARGS" = "hints" ] || [ "$$ARGS" = "help" ]; then \
		./scripts/create_disk.sh --help; \
	else \
		./scripts/create_disk.sh $$ARGS; \
	fi
	@if [ "$$ARGS" != "hints" ] && [ "$$ARGS" != "help" ]; then \
		echo "Disk image is ready: disk.img"; \
	fi

# Delete disk image (useful to reset persistent disk for QEMU)
# Usage: make delete-disk [filesystem] [filename]
# Examples:
#   make delete-disk              # Delete disk.img (default)
#   make delete-disk minix        # Delete disk.img
#   make delete-disk fat32        # Delete fat32.img
#   make delete-disk fat32 fat32.img  # Delete fat32.img explicitly
delete-disk:
	@ARGS="$(filter-out $@,$(MAKECMDGOALS))"; \
	if [ -z "$$ARGS" ]; then \
		./scripts/delete_disk.sh; \
	else \
		./scripts/delete_disk.sh $$ARGS; \
	fi

# Reset dev disk + inject stamps (explicit wipe; ignores IR0_DEV_PERSIST).
disk-reset:
	@DISK=$${DISK:-$(IR0_DISK)}; \
	./scripts/delete_disk.sh $$DISK; \
	rm -f $$DISK.runit.stamp $$DISK.devtools.stamp; \
	echo "✓ disk-reset: $$DISK + inject stamps cleared"

# Load Init binary into virtual disk
# Usage: make load-init [filesystem] [disk_image] [init_binary]
# Defaults: filesystem=auto-detect, disk_image=disk.img, init_binary=setup/pid1/init
# Supported filesystems: minix, fat16, fat32, ext4
# Note: Requires root privileges (mounts filesystem)
# Examples:
#   sudo make load-init                    # Auto-detect, use disk.img
#   sudo make load-init fat32              # Use fat32.img
#   sudo make load-init fat32 fat32.img    # Explicit filesystem and disk
#   make load-init hints                   # Show help
load-init:
	@ARGS="$(filter-out $@,$(MAKECMDGOALS))"; \
	if [ -z "$$ARGS" ]; then \
		./scripts/load_init.sh; \
	elif [ "$$ARGS" = "hints" ] || [ "$$ARGS" = "help" ]; then \
		./scripts/load_init.sh --help; \
	else \
		./scripts/load_init.sh $$ARGS; \
	fi

-include scripts/make/profiles.mk
-include scripts/make/docs.mk
-include scripts/make/pre-submit.mk
-include scripts/make/hostshare-boot.mk
-include scripts/make/boot-audio.mk
-include scripts/make/class-b.mk
-include scripts/make/arm64-board.mk

# QA / smoke / KTM / test targets (see scripts/make/testing.mk)
-include scripts/make/testing.mk

# Host↔guest clipboard via 9p dennis (.ir0/clipboard → guest ir0-paste)
.PHONY: clip-send clip-pull clip-status
IR0_CLIP_DIR = $(KERNEL_ROOT)/.ir0/clipboard

clip-send:
	@chmod +x scripts/ir0-clip.sh
	@scripts/ir0-clip.sh send

clip-pull:
	@chmod +x scripts/ir0-clip.sh
	@scripts/ir0-clip.sh pull

clip-status:
	@chmod +x scripts/ir0-clip.sh
	@scripts/ir0-clip.sh status


# Clean only network objects
clean-net:
	@echo "Cleaning network objects for TAP rebuild..."
	@rm -f net/*.o

# HELP

# DEV TOOLING

format:
	@echo "  FMT     Formatting *.c *.h ..."
	@find . \( -name "*.c" -o -name "*.h" \) \
		-not -path "./setup/*" -not -path "./build/*" -not -path "./.git/*" \
		| xargs clang-format -i
	@echo "✓ Format done"

# Análisis estático con cppcheck (opcional).
analyze:
	@if command -v cppcheck >/dev/null 2>&1; then \
		echo "  CPPCHECK --enable=warning,style --quiet ..."; \
		cppcheck --enable=warning,style --quiet -i.git -iiso -iiso_test .; \
	else \
		echo "cppcheck is not installed; skipping static analysis."; \
		echo "Install cppcheck to enable this target (e.g. apt install cppcheck, dnf install cppcheck, pacman -S cppcheck, brew install cppcheck)."; \
	fi

compile-commands:
	@echo "  CC_JSON Generating compile_commands.json ..."
	@echo "[" > compile_commands.json
	@first=true; count=0; \
	for src in $(patsubst %.o,%.c,$(filter %.o,$(ALL_OBJS))); do \
		if [ -f "$$src" ]; then \
			if [ "$$first" = true ]; then first=false; else echo "," >> compile_commands.json; fi; \
			printf '  { "directory": "%s", "file": "%s", "command": "%s %s -c %s" }' \
				"$(CURDIR)" "$$src" "$(CC)" "$(CFLAGS)" "$$src" >> compile_commands.json; \
			count=$$((count + 1)); \
		fi; \
	done; \
	for src in $(patsubst %.o,%.cpp,$(filter %.o,$(ALL_OBJS))); do \
		if [ -f "$$src" ]; then \
			if [ "$$first" = true ]; then first=false; else echo "," >> compile_commands.json; fi; \
			printf '  { "directory": "%s", "file": "%s", "command": "%s %s -c %s" }' \
				"$(CURDIR)" "$$src" "g++" "$(CXXFLAGS_COMPILE)" "$$src" >> compile_commands.json; \
			count=$$((count + 1)); \
		fi; \
	done; \
	echo "" >> compile_commands.json; \
	echo "]" >> compile_commands.json; \
	echo "✓ compile_commands.json generated ($$count entries)"

disasm: kernel-x64.bin
	@echo "  OBJDUMP kernel-x64.disasm ..."
	@objdump -d -S kernel-x64.bin > kernel-x64.disasm
	@echo "✓ Disassembly: kernel-x64.disasm ($(shell wc -l < kernel-x64.disasm 2>/dev/null || echo ?) lines)"

stack-usage:
	@echo "  STACK   Rebuilding with -fstack-usage ..."
	@$(MAKE) clean
	@$(MAKE) CFLAGS="$(CFLAGS) -fstack-usage" kernel-x64.bin
	@echo ""
	@echo "Top 30 stack consumers:"
	@echo "-----------------------------------------------"
	@find . -name "*.su" -exec cat {} + 2>/dev/null | sort -t: -k3 -rn | head -30
	@echo ""

help:
	@echo "╔════════════════════════════════════════════════════════════╗"
	@echo "║               IR0 KERNEL - BUILD SYSTEM                    ║"
	@echo "╚════════════════════════════════════════════════════════════╝"
	@echo ""
	@echo "Start here (new clone):"
	@echo "  make first-boot PROFILE=minimal   # deps + clone ISD + image + ISO"
	@echo "  make poweron PROFILE=minimal      # persistent installed machine"
	@echo "  make check-env && make defconfig && make ir0"
	@echo "  make sync-mandocs && make man TOPIC=onboarding"
	@echo "  make help-profiles         # kernel board profiles (desktop | hub | watch)"
	@echo "  make pre-submit            # local contributor gate (no push)"
	@echo ""
	@echo "ISD distribution (sibling ../ISD — scripts/make/isd.mk):"
	@echo "  make first-boot PROFILE=minimal|development"
	@echo "  make isdconfig PROFILE=minimal    # extras (.isdconfig)"
	@echo "  make isd / isd-rootfs / isd-image PROFILE=…"
	@echo "  make poweron PROFILE=minimal      # boots persistent IR0-machines disk"
	@echo "  make machine-info | machine-create | image-vmware PROFILE=…"
	@echo "  CONFIRM_RESET=yes make machine-reset PROFILE=…"
	@echo "  make run PROFILE=minimal          # development base-image boot"
	@echo "  make clip-send / clip-pull        # host↔guest clipboard (9p + ir0-paste)"
	@echo "  make clone-isd | check-isd | isd-clean"
	@echo "  Legacy inject (smokes): IR0_LEGACY_USERSPACE=1 make run"
	@echo "  Deprecated alias: bootstrap-userspace → first-boot"
	@echo ""
	@echo "Profiles / images (scripts/make/profiles.mk):"
	@echo "  make help-profiles"
	@echo "  make desktop-x86_64 | hub-rpi4 | watch-rpi5-stub"
	@echo "  make ir0_defconfig PROFILE=… [BOARD=…]"
	@echo "  make sync-menuconfig | sync-menuconfig-defconfig"
	@echo "  make mandocs-from-menuconfig MANDOC_LANG=en   # or: menuconfig key M"
	@echo ""
	@echo "Docs (man pages from Documentation/mandocs):"
	@echo "  make sync-mandocs | man TOPIC=boot | help-docs | mandocs-en"
	@echo ""
	@echo "Build:"
	@echo "  make ir0              Build kernel ISO (-Werror)"
	@echo "  make all              Build kernel ISO"
	@echo "  make windows          Build kernel for Windows (cross-compile)"
	@echo "  make clean            Clean all build artifacts"
	@echo ""
	@echo "Run:"
	@echo "  make run              Run with GUI + disk (recommended)"
	@echo "  make run PROFILE=minimal|development   ISD product disk"
	@echo ""
	@echo "Testing (scripts/make/testing.mk — see scripts/test_catalog.yaml):"
	@echo "  make test             Interactive test TUI (pick suites, R run)"
	@echo "  make test-list        List catalog suites"
	@echo "  make test-run SUITE=host,ktest   Non-interactive (CI / agents)"
	@echo "  make ctr              CTR gates: kernel + arch-guard + matrix-min + host"
	@echo "  make test-fast        arch-guard + tests/host only"
	@echo "  make kernel-tests     In-kernel ktest suite (QEMU)"
	@echo "  make smoke-tier1      Tier-1: runit boot + ash interactive"
	@echo "  make release-0.0.1    Release 0.0.1 gate"
	@echo "  scripts/ir0-qa.sh help   Extended QA / GUI runs / legacy targets"
	@echo "  IR0_LEGACY_SMOKE=1    Historical smoke-fase* (setup/make/legacy-smokes.mk)"
	@echo ""
	@echo "Debug (off by default; rebuild kernel after change):"
	@echo "  IR0_DEBUG_PMM=1       PMM FREE/RECLAIM traces"
	@echo "  IR0_DEBUG_WAIT=1      WAIT_EXIT_AUDIT / CTX resume traces"
	@echo "  IR0_DEBUG_PROC=1      Process lifecycle traces"
	@echo ""
	@echo "Dev Tooling:"
	@echo "  make format           Format all C/H files with clang-format"
	@echo "  make analyze          Run cppcheck (warning,style) if installed"
	@echo "  make compile-commands Generate compile_commands.json for LSP/IDE"
	@echo "  make disasm           Disassemble kernel binary (objdump -d -S)"
	@echo "  make stack-usage      Rebuild with -fstack-usage and show top consumers"
	@echo "Build uses -j\$$(nproc) by default (override: make -j1 or PARALLEL_JOBS=4)."
	@echo ""
	@echo "Utilities:"
	@echo "  make menuconfig       Kernel configuration menu (curses TUI)"
	@echo "  make menuconfig-en    Open menuconfig with English UI"
	@echo "  make menuconfig-es    Open menuconfig with Spanish UI"
	@echo "  make defconfig        Write default .config (all features enabled)"
	@echo "  make sync-menuconfig  Merge new Kconfig symbols into .config (safe)"
	@echo "  make sync-menuconfig-defconfig  Refresh setup/defconfig from Kconfig"
	@echo "  make sync-menuconfig-check      Dry-run: show config drift vs Kconfig"
	@echo "  make check-env | deptest   Host env diagnostic (default desktop-x86_64)"
	@echo "  make deptest PROFILE=desktop-x86_64|userspace|minimal|hub-rpi4|watch|all"
	@echo "  make pre-submit [SUBSYSTEM=mm|net|arm64]   Local gate → PRE_SUBMIT_OK"
	@echo "  make tests | kernel-memsafe | kernel-analyze | health | arch-guard"
	@echo "  make ktm-check | linux-abi-audit | ktm-report"
	@echo "  make create-disk | load-init | disk-reset"
	@echo "  IR0_DEV_PERSIST=1     Reuse disk/stamps across local smokes (not CI)"
	@echo "  make mandocs | mandocs-en | mandocs-es | help-docs"
	@echo "  make help             Show this help"
	@echo ""
	@echo "Extern Drivers (Multi-Language):"
	@echo "  make en-ext-drv       Enable example drivers for next build"
	@echo "  make dis-ext-drv      Disable example drivers"
	@echo "  Note: Extern drivers are optional and disabled by default"
	@echo ""
	@echo "Unibuild - Isolated Compilation:"
	@echo "  C files (can compile multiple at once):"
	@echo "    make unibuild <file1.c> [file2.c] ..."
	@echo "    make unibuild-win <file1.c> [file2.c] ...     (Windows)"
	@echo ""
	@echo "  C++ files (can compile multiple at once):"
	@echo "    make unibuild-cpp <file1.cpp> [file2.cpp] ..."
	@echo "    make unibuild-cpp-win <file1.cpp> [file2.cpp] ...  (Windows)"
	@echo ""
	@echo "  Rust files (can compile multiple at once):"
	@echo "    make unibuild-rust <file1.rs> [file2.rs] ..."
	@echo "    make unibuild-rust-win <file1.rs> [file2.rs] ...   (Windows)"
	@echo ""
	@echo "  Clean:"
	@echo "    make unibuild-clean <file>"
	@echo ""
	@echo "  Examples:"
	@echo "    make unibuild fs/tmpfs.c"
	@echo "    make unibuild fs/tmpfs.c fs/vfs.c fs/path.c"
	@echo "    make unibuild-cpp cpp/examples/cpp_example.cpp"
	@echo "    make unibuild-rust rust/drivers/rust_simple_driver.rs"
	@echo "    make unibuild-win drivers/IO/ps2.c"
	@echo "    make unibuild-cpp-win cpp/examples/cpp_example.cpp"
	@echo ""
	@echo "  Note: You can also use \"file1 file2\" syntax"
	@echo ""
	@echo "Quick start: make run"
	@echo ""

# DEPENDENCY TEST

deptest check-env:
	@chmod +x $(KERNEL_ROOT)/scripts/deptest.sh
	@PROFILE="$(PROFILE)" BOARD="$(BOARD)" $(KERNEL_ROOT)/scripts/deptest.sh

# UNIBUILD - ISOLATED FILE COMPILATION

# Helper to get file arguments (supports multiple files from FILE= or positional)
# Usage in targets: $(call get-file-arg)
define get-file-arg
$(if $(FILE),$(FILE),$(filter-out $@,$(MAKECMDGOALS)))
endef

# Standard C compilation (supports multiple files)
unibuild:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild <file1.c> [file2.c] ..."; \
		echo "   Or: make unibuild \"<file1.c>  <file2.c>\""; \
		echo "Example: make unibuild fs/tmpfs.c"; \
		echo "Example: make unibuild fs/tmpfs.c fs/vfs.c"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh $$FILE_ARG

# C++ compilation (supports multiple files)
unibuild-cpp:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild-cpp <file1.cpp> [file2.cpp] ..."; \
		echo "   Or: make unibuild-cpp \"<file1.cpp> <file2.cpp>\""; \
		echo "Example: make unibuild-cpp cpp/examples/cpp_example.cpp"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh -cpp $$FILE_ARG

# Rust compilation (supports multiple files)
unibuild-rust:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild-rust <file1.rs> [file2.rs] ..."; \
		echo "   Or: make unibuild-rust \"<file1.rs> <file2.rs>\""; \
		echo "Example: make unibuild-rust rust/drivers/rust_simple_driver.rs"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh -rust $$FILE_ARG

# Windows cross-compilation (C, supports multiple files)
unibuild-win:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild-win <file1.c> [file2.c] ..."; \
		echo "   Or: make unibuild-win \"<file1.c> <file2.c>\""; \
		echo "Example: make unibuild-win drivers/IO/ps2.c"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh -win $$FILE_ARG

# Windows cross-compilation (C++, supports multiple files)
unibuild-cpp-win:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild-cpp-win <file1.cpp> [file2.cpp] ..."; \
		echo "   Or: make unibuild-cpp-win \"<file1.cpp> <file2.cpp>\""; \
		echo "Example: make unibuild-cpp-win cpp/examples/cpp_example.cpp"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh -win -cpp $$FILE_ARG

# Windows cross-compilation (Rust, supports multiple files)
unibuild-rust-win:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild-rust-win <file1.rs> [file2.rs] ..."; \
		echo "   Or: make unibuild-rust-win \"<file1.rs> <file2.rs>\""; \
		echo "Example: make unibuild-rust-win rust/drivers/rust_simple_driver.rs"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh -win -rust $$FILE_ARG

# Catch-all target to prevent make from complaining about unknown targets (for positional args)
%:
	@:

unibuild-clean:
	@if [ -z "$(FILE)" ]; then \
		echo "Error: FILE parameter required"; \
		echo "Usage: make unibuild-clean <source_file>"; \
		echo "Example: make unibuild-clean fs/tmpfs.c"; \
		exit 1; \
	fi
	@$(KERNEL_ROOT)/scripts/unibuild-clean.sh "$(FILE)"

# TEST DRIVERS - MULTI-LANGUAGE EXAMPLES (OPTIONAL)

# Rust test driver
RUST_TEST_DRIVER = rust/drivers/rust_simple_driver.rs
RUST_TEST_OBJ = rust/drivers/rust_simple_driver.o

# C++ test driver
CPP_TEST_DRIVER = cpp/examples/cpp_example.cpp
CPP_TEST_OBJ = cpp/examples/cpp_example.o

# Enable example drivers for next build
en-ext-drv:
	@echo "ENABLE_EXAMPLE_DRIVERS=1" > .example_drivers_enabled
	@echo "✓ Example drivers enabled - will be compiled on next build"

# Disable example drivers
dis-ext-drv:
	@rm -f .example_drivers_enabled
	@echo "✓ Example drivers disabled - will not be compiled"

# Compile Rust test driver using unibuild
test-driver-rust: $(RUST_TEST_DRIVER)
	@echo "🦀 Compiling Rust test driver with unibuild..."
	@$(KERNEL_ROOT)/scripts/unibuild.sh -rust $(RUST_TEST_DRIVER)
	@if [ -f $(RUST_TEST_OBJ) ]; then \
		echo "✓ Rust driver compiled: $(RUST_TEST_OBJ)"; \
	else \
		echo "✗ Rust driver compilation failed"; \
		exit 1; \
	fi

# Compile C++ test driver using unibuild
test-driver-cpp: $(CPP_TEST_DRIVER)
	@echo "➕ Compiling C++ test driver with unibuild..."
	@$(KERNEL_ROOT)/scripts/unibuild.sh -cpp $(CPP_TEST_DRIVER)
	@if [ -f $(CPP_TEST_OBJ) ]; then \
		echo "✓ C++ driver compiled: $(CPP_TEST_OBJ)"; \
	else \
		echo "✗ C++ driver compilation failed"; \
		exit 1; \
	fi

# Compile all test drivers (standalone compilation, not included in kernel)
test-drivers: test-driver-rust test-driver-cpp
	@echo ""
	@echo "╔════════════════════════════════════════════════════════════╗"
	@echo "║          TEST DRIVERS COMPILATION COMPLETE                 ║"
	@echo "╚════════════════════════════════════════════════════════════╝"
	@echo ""
	@echo "✓ Rust driver:  $(RUST_TEST_OBJ)"
	@echo "✓ C++ driver:   $(CPP_TEST_OBJ)"
	@echo ""
	@echo "Note: These are standalone objects. To include in kernel build:"
	@echo "      make en-ext-drv && make ir0"
	@echo "      make dis-ext-drv && make ir0"
	@echo ""

# Clean test driver objects
# Clean test driver objects
test-drivers-clean:
	@echo "Cleaning test driver objects..."
	@if [ -n "$(RUST_ONLY)" ]; then \
		rm -f $(RUST_TEST_OBJ); \
		echo "✓ Rust driver objects cleaned"; \
	elif [ -n "$(CPP_ONLY)" ]; then \
		rm -f $(CPP_TEST_OBJ); \
		echo "✓ C++ driver objects cleaned"; \
	else \
		rm -f $(RUST_TEST_OBJ); \
		rm -f $(CPP_TEST_OBJ); \
		echo "✓ All test driver objects cleaned"; \
	fi


# PHONY TARGETS

.PHONY: all clean run run-debug run-dbgshell run-tap run-nodisk run-console run-gdb debug create-disk delete-disk disk-reset load-init remove-init help \
        unibuild unibuild-cpp unibuild-rust unibuild-win unibuild-cpp-win unibuild-rust-win unibuild-clean \
        ir0 ir0-auto auto windows win windows-clean win-clean deptest check-env pre-submit menuconfig menuconfig-en menuconfig-es defconfig sync-menuconfig sync-menuconfig-defconfig sync-menuconfig-check \
        en-ext-drv dis-ext-drv \
        test-driver-rust test-driver-cpp test-drivers test-drivers-clean \
        tests kernel-memsafe kernel-tests kernel-analyze analyze health build-matrix-min build-matrix-full config-sim arch-guard repo-hygiene-guard mandocs mandocs-en mandocs-es mandocs-view mandocs-uninstall ai-dev-rules-install \
        build-linux-abi-brk-probe build-linux-abi-wait4-probe build-linux-abi-read-probe \
        build-linux-abi-mmap-probe build-linux-abi-mount-probe build-linux-abi-openat-probe \
        build-linux-abi-stat-probe \
        linux-abi-audit linux-abi-audit-brk linux-abi-audit-wait4 linux-abi-audit-read \
        linux-abi-audit-mmap linux-abi-audit-mount linux-abi-audit-openat linux-abi-audit-stat \
        runtime-net-check runtime-mount-check smoke-qemu smoke-userspace-init smoke-userspace-musl smoke-musl-arch-prctl smoke-userspace-shell smoke-userspace-segv smoke-real-hw smoke-all smoke-fase53b-posix-pseudofs smoke-fase54a-fbdev smoke-fase54b-input smoke-fase54c-input-deterministic smoke-fase55a-doom-prereq smoke-fase55b-doom-stub smoke-fase55c-timing-input smoke-fase55d-doomgeneric smoke-current-fase54b smoke-regression-light smoke-regression-light-fast smoke-regression-full \
        build-init-smoke build-init-musl build-musl-arch-prctl-smoke build-init-minimal build-init-segv-smoke build-sh-smoke build-userspace-segv build-ktm-posix-pseudofs-smoke build-init-heart-smoke build-ktm-fbdev-smoke build-ktm-input-smoke build-ktm-input-det-smoke build-ktm-doom-prereq-smoke build-ktm-doom-stub build-ktm-doom-timing-stub build-ktm-doomgeneric-smoke build-ktm-doom-interactive run-fase55d-doomgeneric-gui build-ktm-boot-halt-bin build-ktm-fbdev-gui-bin run-fase58c-boot-gui run-fase58c-fbdev-gui run-fase58c-doom-gui check-fase58c-logs run-fase58e-ash-gui check-fase58e-logs         smoke-fase58e-ash-interactive build-busybox-fase58-full build-ktm-busybox-manifest-smoke smoke-fase58l-busybox-coreutils smoke-busybox-manifest build-irinit run-irinit-interactive-gui kernel-x64-userspace.bin kernel-x64-userspace.iso kernel-x64-userspace-lazy.bin kernel-x64-userspace-lazy.iso smoke-mm-cow-lazy load-init-with-smoke load-init-with-musl load-userspace-rootfs \
        roadmap-phase1-stability roadmap-phase2-driver-expansion roadmap-phase3-core-features \
        scale-readiness-gate config-wiring-check arch-config-check \
        format compile-commands disasm stack-usage clean-net \
        run-ping

# Include dependency files
-include $(ALL_OBJS:.o=.d)
